name: Build AimeBot APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build'
        required: false
        default: '1.0'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Briefcase
      run: |
        pip install --upgrade pip
        pip install briefcase toga requests
    
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Build APK
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        briefcase create android
        briefcase build android
        briefcase package android
    
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: AimeBot-APK
        path: dist/*.apk
        if-no-files-found: error
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.apk
